

services:
  postgresql:
    build: ./postgresql
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: postgres
    ports:
      - "5432:5432"
    volumes:
      -  "pgdata:/bitnami/postgresql"
    networks:
      - puppetnet

#  puppetdb:
#    build: ./puppetdb
#    container_name: puppetdb
#    restart: always
#    depends_on:
#      - postgresql
#    ports:
#      - "8081:8081"
#    networks:
#      - puppetnet

networks:
  puppetnet:
    driver: bridge

volumes:
  pgdata: